### ISSUE TITLE
As a ROS2 user, I can depend easily on wjwwood/serial so that my ROS2 code can communicate with rs232 peripherals

### ISSUE THREAD

**Issue by emersonknapp** [ros-tooling/aws-roadmap#75]
## Description

- [x] Convert build system from `catkin` to `ament`
- [ ] Do bloom-release in Dashing or Eloquent.

Should be done in the ROS 2 branch.

## Documents

* https://github.com/wjwwood/serial/issues/204

## Completion Criteria

* Test that Debian packages (Dashing/Eloquent) are working
* Ensure wjwwood/serial#204 is closed

**Comment by zmichaels11** [comment]
Rewriting CMakeLists.txt to use `ament`

**Comment by zmichaels11** [comment]
Marked `milestone` as `Sprint #6` since this was started late on Thursday, Nov 07 (during sprint 6)

**Comment by zmichaels11** [comment]
### To Do:
- [ ] Convert project build from `catkin` to `ament`
- [ ] Convert test build from `catkin` to `ament`
- [ ] Run linters with `colcon test`
- [ ] Run tests with `colcon test`

**Comment by zmichaels11** [comment]
After rewriting `CMakeLists.txt` to `ament`, this package fails every linter with several changes required from `uncrustify` and `cpplint`

`-Werror=sign-compare` and `-Werror=unused-but-set-variable` caused multiple errors in `list_ports_linux.cc`

This task might need to be repointed due to amount of rewrite required.

**Comment by thomas-moulard** [comment]
Could we just disable the linters?

**Comment by zmichaels11** [comment]
`'boost/bind.hpp' file not found` on macOS GH Action; testing on local machine

**Comment by thomas-moulard** [comment]
Is it in a test, boost is only listed as a test_depend, that may be the problem here.

**Comment by zmichaels11** [comment]
It is listed in the test `tests/unix_serial_tests.cc`

**Comment by thomas-moulard** [comment]
Then it may be a problem with my `rosdep` invocation in the CI, I'd check and see if boost is getting installed or not. My guess is that it's not pulled properly (maybe rosdep does not include test dep by default, that would make sense?), and it just happens to work in most cases because Ubuntu is probably pre-loaded with Boost, but not the OS X worker? Also, you're unlikely to be able to repro locally if you have boost installed.

**Comment by zmichaels11** [comment]
Boost is installed on OSX, however its CMake files are being skipped.

* The ROS1 code for serial also targets hydro. It might be a good idea to spin off a user story requesting it to be upgraded to a more recent ROS1.

**Comment by zmichaels11** [comment]
Boost was safely removed as a dependency.
Build and test for OSX + Ubuntu 18.04: [![Actions Status](https://github.com/zmichaels11/serial/workflows/Test%20serial/badge.svg)](https://github.com/zmichaels11/serial/actions)

**Comment by zmichaels11** [comment]
@zmichaels11 add user story to bring serial to updated ros1 distro

**Comment by piraka9011** [comment]
It looks like bringing this package up to speed to both ROS1 and 2 will require more refactoring and more use stories. 
We should decide as a team whether we want to commit to supporting this further or not maintaining it.

**Comment by piraka9011** [comment]
Closing since we won't be supporting this.

**Comment by zmichaels11** [comment]
Not planing to do anymore
